// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "7251202ab48958271a29386c0b3aa33d1121b39a6c4f0c2cc14b26d779e533dd")
