// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "afdaf47345fc6b643f6963121a6a64676f6aac3cb45de9249e44e133063b98b0")
